[providers]
php = "8.2"

[variables]
PORT = "8080"

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.gd", "nodejs_18"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t theme/"
